# Generated by Django 5.0.7 on 2024-07-20 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esta_disponible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueno_local', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.local')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_comienzo', models.DateField()),
                ('final_dia', models.DateField()),
                ('totalpagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locales.local')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
