# Generated by Django 5.1 on 2024-08-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puplicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
