# Generated by Django 5.1.1 on 2024-09-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puplicaciones', '0002_alquiler_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='aire_acondicionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='amueblado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='ano_construccion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='calefaccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='mascotas_permitidas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='num_banos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='num_garajes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='num_habitaciones',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='piscina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='tiene_balcon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='tiene_patio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='tipo_propiedad',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('chalet', 'Chalet'), ('duplex', 'Dúplex'), ('piso', 'Piso')], default='casa', max_length=100),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
