# Generated by Django 5.1.1 on 2024-09-07 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puplicaciones', '0003_alquiler_aire_acondicionado_alquiler_amueblado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='alquileres/')),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='puplicaciones.alquiler')),
            ],
        ),
    ]
