# Generated by Django 5.1.1 on 2024-09-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puplicaciones', '0005_remove_alquiler_image_url_remove_alquiler_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenalquiler',
            name='image_url',
        ),
    ]
