# Generated by Django 5.1.1 on 2024-09-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='defaultProfile.jpg', upload_to='profile_perfil/'),
        ),
    ]
