# Generated by Django 5.1.1 on 2024-10-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
